server.port: 8080

jwt.secretKey: kjhdklsjdweisndlj1heiue3e27e87asdnaiudq8o7dbuysdddln5o87y
eureka:
  client:
     service-url:
         defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
           - id: user-service
             uri: ${USER_SERVICE_URI:lb://USER-SERVICE}
             predicates:
              - Path=/api/v1/users/**
             filters:
              - StripPrefix=2

           - id: post-service
             uri: ${POST_SERVICE_URI:lb://POST-SERVICE}
             predicates:
              - Path=/api/v1/posts/**
             filters:
              - StripPrefix=2
              - name: AuthenticationFilter

           - id: connection-service
             uri: ${CONNECTION_SERVICE_URI:lb://CONNECTION-SERVICE}
             predicates:
              - Path=/api/v1/connections/**
             filters:
              - StripPrefix=2
              - name: AuthenticationFilter

           - id: notification-service
             uri: ${NOTIFICATION_SERVICE:lb://NOTIFICATION-SERVICE}
             predicates:
               - Path=/api/v1/notifications/**
             filters:
               - StripPrefix=2
               - name: AuthenticationFilter



