apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: post-db
spec:
  selector:
    matchLabels:
      app: post-db
  serviceName: post-db
  replicas: 1
  template:
    metadata:
      labels:
        app: post-db
    spec:
      containers:
      - name: post-db
        image: postgres:16
        resources:
          limits:
              memory: "200Mi"
              cpu: "200m"
          requests:
            memory: "100Mi"
            cpu: "100m"
        env:
          - name: POSTGRES_USER
            value: user
          - name: POSTGRES_PASSWORD
            value: password
          - name: POSTGRES_DB
            value: postDB
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: "standard-rwo" 
      volumeMode: Filesystem

---

apiVersion: v1
kind: Service
metadata:
  name: post-db
spec:
  clusterIP: None
  selector:
    app: post-db
  ports:
  - port: 5432
    targetPort: 5432

